spring:
  application:
    name: http-proxy-service
  cloud:
    gateway:
      routes:
        - id: rpcipv4
          uri: http://sbhomta11.vzbi.com:8008/ipm-webservices/ipv4Service?wsdl
          predicates:
            - Path=/ipm/consumer/soap/rpc/ipv4/**
          filters:
            - StripPrefix=2
        - id: rpcipv6
          uri: http://sbhomta11.vzbi.com:8008/ipv6-webservice/ipv6Service?WSDL
          predicates:
            - Path=/ipm/consumer/soap/rpc/ipv6/**
          filters:
            - StripPrefix=2
        - id: wsipv4
          uri: http://sbhomta11.vzbi.com:8008/IpmServiceEJB/ipv4JAXWSService?wsdl
          predicates:
            - Path=/ipm/consumer/soap/ws/ipv4/**
          filters:
            - StripPrefix=2
        - id: wsipv6
          uri: http://sbhomta11.vzbi.com:8008/IpmServiceEJB/ipv6JAXWSService?wsdl
          predicates:
            - Path=/ipm/consumer/soap/ws/ipv6/**
          filters:
            - StripPrefix=2
        - id: rdns
          uri: http://sbhomta11.vzbi.com:8089/rdns/uploadzone
          predicates:
            - Path=/ipm/rdns/**
          filters:
            - StripPrefix=2
        - id: rpcipv4proxy
          uri: https://inam-qa-sso.ebiz.verizon.com/ipm/consumer/soap/rpc/ipv4Service?wsdl
          predicates:
            - Path=/ipm/consumer/soap/rpc/proxy/ipv4/**
          filters:
            - StripPrefix=2
        - id: rpcipv6proxy
          uri: https://inam-qa-sso.ebiz.verizon.com/ipm/consumer/soap/rpc/ipv6Service?wsdl
          predicates:
            - Path=/ipm/consumer/soap/rpc/proxy/ipv6/**
          filters:
            - StripPrefix=2
        - id: wsipv4proxy
          uri: https://inam-qa-sso.ebiz.verizon.com/ipm/consumer/soap/ws/ipv4Service?wsdl
          predicates:
            - Path
